[build]
publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Content-Security-Policy = "report-uri https://illvart.report-uri.com/r/d/ct/reportOnly"
    Expect-CT = """
      max-age=0, report-uri="https://illvart.report-uri.com/r/d/ct/reportOnly"
    """

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache"
    X-UA-Compatible = "IE=Edge"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "immutable, max-age=31536000"
    Accept-Encoding = "gzip, deflate, br"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "immutable, max-age=31536000"
    Accept-Encoding = "gzip, deflate, br"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "immutable, max-age=31536000"
